[project]
name = 'nexus-verse-gaming-protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.nexus-verse-gaming]
path = 'contracts/nexus-verse-gaming.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
